fixed search

diff --git a/sh/archibold b/sh/archibold
--- a/sh/archibold
+++ b/sh/archibold
@@ -48,11 +48,8 @@ installation() {
       ;;
     *)
       if [ "$(sudo pacman -Qs $name)" = "" ]; then
-        AUR=curl -s -I $(getAURPackageNameAsURL $name) | grep '404'
+        AUR=$(curl -s -I $(getAURPackageNameAsURL $name) | grep '404')
         if [ "$AUR" = "" ]; then
-          echo -e "${RED}[WARNING]${RESET} package ${BOLD}${1}${RESET} not found";
-          exit 1
-        else
           echo -e "Found an unknown AUR ${BOLD}${1}${RESET} package."
           read -n1 -r -p "Are you sure you would like to install it? [y/N]" AUR
           if [ "$AUR" = "Y" ]; then
@@ -61,6 +58,9 @@ installation() {
           if [ "$AUR" = "y" ]; then
             commonProcedure $name
           fi
+        else
+          echo -e "${RED}[WARNING]${RESET} package ${BOLD}${1}${RESET} not found";
+          exit 1
         fi
       else
         sudo pacman -S --needed --noconfirm $name
@@ -126,7 +126,7 @@ archibold() {
       ;;
     search)
       if [ "$(sudo pacman -Qs $2)" = "" ]; then
-        AUR=curl -s -I $(getAURPackageNameAsURL $name) | grep '404'
+        AUR=$(curl -s -I $(getAURPackageNameAsURL $2) | grep '404')
         if [ "$AUR" = "" ]; then
           echo -e "${BOLD}${2}${RESET} available only via ${BOLD}AUR${RESET}"
         else
