using error code too and added no-pg-keys

diff --git a/utils/aur b/utils/aur
--- a/utils/aur
+++ b/utils/aur
@@ -39,12 +39,12 @@ aur() {
     cd ${pkg}
     makepkg -Asfc --needed --noconfirm
     echo ""
-    if [ "$(ls ${pkg}*.pkg.tar.xz 2> /dev/null)" != "" ]; then
+    if [ "$?" = "0" ] && [ "$(ls ${pkg}*.pkg.tar.xz 2> /dev/null)" != "" ]; then
       echo "$(tput bold)Created$(tput sgr0): ~/tmp-${pkg}/${pkg}/$(ls ${pkg}*.pkg.tar.xz)"
       sleep 1
       su -c "pacman -U --noconfirm $(ls ${pkg}*.pkg.tar.xz)"
     else
-      echo "$(tput bold)Error$(tput sgr0): ${pkg}*.tar.xz not found"
+      echo "$(tput bold)Error$(tput sgr0) $?: ${pkg}*.tar.xz not found"
     fi
     if [ "${preserve}" != "--preserve" ]; then
       echo "cleaning up"
