using zst too

diff --git a/utils/aur b/utils/aur
--- a/utils/aur
+++ b/utils/aur
@@ -5,6 +5,7 @@
 #########################
 
 aur() {
+  local build=""
   local pkg=""
   local preserve=""
   local skippgp=""
@@ -72,16 +73,17 @@ aur() {
     echo "Making $(tput bold)${pkg}$(tput sgr0) package"
     makepkg -Asfc --needed --noconfirm ${skippgp}
     echo ""
-    if [ "$?" = "0" ] && [ "$(ls ${pkg}*.pkg.tar.xz 2> /dev/null)" != "" ]; then
-      echo "$(tput bold)Created$(tput sgr0): ~/tmp-${pkg}/${pkg}/$(ls ${pkg}*.pkg.tar.xz)"
+    if [ "$?" = "0" ] && [ "$(ls ${pkg}*.pkg.tar.{xz,zst} 2> /dev/null)" != "" ]; then
+      build="$(ls ${pkg}*.pkg.tar.{xz,zst})"
+      echo "$(tput bold)Created$(tput sgr0): ~/tmp-${pkg}/${pkg}/${build}"
       sync
       if [ "$AUR_NO_SUDO" != "" ] || [ "$HAS_SUDO" = "0" ]; then
-        su -c "yes y | pacman -U $(ls ${pkg}*.pkg.tar.xz)"
+        su -c "yes y | pacman -U ${build}"
       else
-        sudo sh -c "yes y | pacman -U $(ls ${pkg}*.pkg.tar.xz)"
+        sudo sh -c "yes y | pacman -U ${build}"
       fi
     else
-      echo "$(tput bold)Error$(tput sgr0) $?: ${pkg}*.tar.xz not found"
+      echo "$(tput bold)Error$(tput sgr0) $?: ${pkg}*.tar.{xz,zst} not found"
     fi
     if [ "${preserve}" != "--preserve" ]; then
       echo "cleaning up"
